export const ROUTES = {
  // Public
  HOME:        '/',
  ABOUT:       '/about',
  SERVICES:    '/services',
  PRICING:     '/pricing',
  CONTACT:     '/contact',
  // Auth
  LOGIN:       '/auth/login',
  REGISTER:    '/auth/register',
  FORGOT:      '/auth/forgot-password',
  RESET:       '/auth/reset-password/:token',
  // Admin
  ADMIN:            '/admin',
  ADMIN_USERS:      '/admin/users',
  ADMIN_REPORTS:    '/admin/reports',
  ADMIN_VERIF:      '/admin/verifications',
  ADMIN_SETTINGS:   '/admin/settings',
  // Exporter
  EXPORTER:          '/exporter',
  EXPORTER_PRODUCTS: '/exporter/products',
  EXPORTER_ADD_PROD: '/exporter/products/add',
  EXPORTER_ORDERS:   '/exporter/orders',
  EXPORTER_REQUESTS: '/exporter/buyer-requests',
  EXPORTER_DOCS:     '/exporter/documents',
  EXPORTER_SHIPS:    '/exporter/shipments',
  EXPORTER_WALLET:   '/exporter/wallet',
  EXPORTER_MSGS:     '/exporter/messages',
  // Buyer
  BUYER:             '/buyer',
  BUYER_MARKETPLACE: '/buyer/marketplace',
  BUYER_PRODUCT:     '/buyer/marketplace/:id',
  BUYER_ORDERS:      '/buyer/orders',
  BUYER_FAVORITES:   '/buyer/favorites',
  BUYER_MSGS:        '/buyer/messages',
  BUYER_SETTINGS:    '/buyer/settings',
  // Shipper
  SHIPPER:           '/shipper',
  SHIPPER_TRACKING:  '/shipper/tracking',
  SHIPPER_REPORTS:   '/shipper/reports',
}
